name: pomdp10
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - conda-forge
dependencies:
  - python=3.10.12
  - ffmpeg
  - fonttools
  - gcc=15.2.0
  - hdf5
  - markdown
  - matplotlib-base=3.10.6
  - mkl
  - mysql
  - networkx
  - numexpr
  - numpy-base=1.26.4
  - opencv
  - packaging
  - pandas
  - pillow
  - pip=25.3
  - psutil
  - pyparsing
  - pytorch-mutex
  - pyyaml
  - requests
  - ruamel.yaml=0.18.16
  - scikit-learn
  - scipy
  - setuptools=72.1.0
  - sqlite
  - tensorboard
  - typing_extensions
  - werkzeug
  - wheel
  - yaml
  - zstd
  - pip:
      - absl-py
      - cloudpickle
      - etils
      - farama-notifications
      - fsspec
      - glfw
      - gymnasium
      - imageio
      - imageio-ffmpeg
      - importlib-resources
      - metaworld==3.0.0
      - mujoco==3.3.7
      - numpy
      - pyopengl
      - pyopengl-accelerate
      - torch
      - torchvision
      - tqdm
      - zipp
variables:
  MUJOCO_GL: egl
  PYOPENGL_PLATFORM: egl
